export default {
  FEEDS_RECEIVED:          'FEEDS_RECEIVED',
  FEED_CREATED:            'FEED_CREATED',
  SELECTED_FEED:           'SELECTED_FEED',
	USERS_RECEIVED: 		     'USERS_RECEIVED',
	USER_CREATED: 			     'USER_CREATED',
	USER_LOGGED_IN: 		     'USER_LOGGED_IN',
	CURRENT_USER_RECEIVED:   'CURRENT_USER_RECEIVED'
}
